/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fluigdocdev.views;

import fluigdocdev.entidades.Cliente;
import fluigdocdev.entidades.Projeto;
import fluigdocdev.entidades.ArqProjet;
import fluigdocdev.SqliteConnect;
import fluigdocdev.FileSystemModel;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rogerio
 */
public class CadastroProjeto extends javax.swing.JInternalFrame {

    SqliteConnect sql = new SqliteConnect();
    Cliente cli = new Cliente();
    Projeto proj = new Projeto();
    ArqProjet arq = new ArqProjet();

    /**
     * Creates new form CadastroProjeto
     */
    public CadastroProjeto() {
        initComponents();
        loadCbProjt();
    }

    private void loadCbProjt() {
        try {
            this.cbCliente.setModel(sql.getResultComboBoxModel(cli.getSelNomeCli()));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbProjetos = new javax.swing.JTable();
        cbCliente = new javax.swing.JComboBox<>();
        lbProjeto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        lbCliente = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbArq = new javax.swing.JTable();
        cbProjeto = new javax.swing.JComboBox<>();
        btNovoProjeto = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setClosable(true);
        setMaximizable(true);
        setTitle("Cadastro de Projetos");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tbProjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Projetos"
            }
        ));
        tbProjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProjetosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProjetos);

        cbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClienteActionPerformed(evt);
            }
        });

        lbProjeto.setText("Projeto:");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("SelecioneumProjeto");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTree1);

        lbCliente.setText("Cliente:");

        tbArq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Dados"
            }
        ));
        tbArq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbArqMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbArq);

        cbProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProjetoActionPerformed(evt);
            }
        });

        btNovoProjeto.setText("Novo Projeto");
        btNovoProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoProjetoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCliente)
                        .addGap(1, 1, 1)
                        .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbProjeto)
                        .addGap(2, 2, 2)
                        .addComponent(cbProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNovoProjeto))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCliente)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbProjeto)
                    .addComponent(cbProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNovoProjeto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClienteActionPerformed
        // TODO add your handling code here:
        String descCli = (String) this.cbCliente.getSelectedItem();  
        cli.setNome(descCli);
        try {
            String url = sql.getUnicValue(cli.getSelUrlCli());          
            File file = new File(url);
            FileSystemModel model = new FileSystemModel(file);
            this.jTree1.setModel(model);            
            this.cbProjeto.setModel(this.proj.getArqModelCB(descCli));
            this.tbProjetos.setModel(this.proj.getArqModel(descCli));
        } catch (Exception e) {
            System.err.println("Erro: " + e.getMessage());
        }

    }//GEN-LAST:event_cbClienteActionPerformed

    private void btNovoProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoProjetoActionPerformed
        // TODO add your handling code here:
        if (this.cbCliente.getSelectedItem().equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Selecione um Cliente!");
        } else {
            String projeto = JOptionPane.showInputDialog("Digite o Nome do Novo Projeto");
            if (projeto.trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Nome de Projeto está em branco");
            } else {
                try {
                    String descCli = (String) this.cbCliente.getSelectedItem();
                    this.proj.setProject(descCli, projeto);
                    this.cbProjeto.setModel(this.proj.getArqModelCB(descCli));
                    this.tbProjetos.setModel(this.proj.getArqModel(descCli));
                } catch (SQLException ex) {
                    Logger.getLogger(CadastroProjeto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_btNovoProjetoActionPerformed

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        if (evt.getClickCount() == 2) {
            if (!this.cbProjeto.getSelectedItem().equals("Selecione")) {
                try {
                    this.arq.setArq(this.jTree1.getSelectionPath(), (String) this.cbProjeto.getSelectedItem());
                    this.tbArq.setModel(this.arq.getArqModel((String) this.cbProjeto.getSelectedItem()));
                } catch (SQLException ex) {
                    Logger.getLogger(CadastroProjeto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jTree1MouseClicked

    private void cbProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProjetoActionPerformed
        // TODO add your handling code here:
        if (!this.cbProjeto.getSelectedItem().equals("Selecione")) {
            try {
                this.tbArq.setModel(this.arq.getArqModel((String) this.cbProjeto.getSelectedItem()));
            } catch (SQLException ex) {
                Logger.getLogger(CadastroProjeto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cbProjetoActionPerformed

    private void tbArqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbArqMouseClicked
        // TODO add your handling code here:
        if (!tbArq.getValueAt(tbArq.getSelectedRow(), 0).toString().equals("")) {
            int isDel = JOptionPane.showConfirmDialog(null,
                    "Deseja Deletar o Arquivo: "
                    + tbArq.getValueAt(tbArq.getSelectedRow(), 1).toString()
                    + " - Tipo: "
                    + tbArq.getValueAt(tbArq.getSelectedRow(), 5).toString()
            );
            System.out.println("isDel: " + isDel);
            if (isDel == 0) {
                this.arq.setId(tbArq.getValueAt(tbArq.getSelectedRow(), 0).toString());
                try {
                    this.arq.setDelArq();
                    this.tbArq.setModel(this.arq.getArqModel((String) this.cbProjeto.getSelectedItem()));
                } catch (SQLException ex) {
                    Logger.getLogger(CadastroProjeto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_tbArqMouseClicked

    private void tbProjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProjetosMouseClicked
        // TODO add your handling code here:
        if (!tbProjetos.getValueAt(tbProjetos.getSelectedRow(), 0).toString().equals("")) {
            int isDel = JOptionPane.showConfirmDialog(null,
                    "Deseja Deletar o Projeto: "
                    + tbProjetos.getValueAt(tbProjetos.getSelectedRow(), 1).toString()
            );
            System.out.println("isDel: " + isDel);
            if (isDel == 0) {
                String descCli = (String) this.cbCliente.getSelectedItem();
                this.proj.setId(tbProjetos.getValueAt(tbProjetos.getSelectedRow(), 0).toString());
                try {                   
                   this.proj.setDelArq();
                   //this.cbProjeto.setModel(this.sql.getResultComboBoxModel(this.proj.getSelProjCB()));
                   this.cbProjeto.setModel(this.proj.getArqModelCB(descCli));
                   this.tbProjetos.setModel(this.proj.getArqModel(descCli));
                } catch (SQLException ex) {
                    Logger.getLogger(CadastroProjeto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_tbProjetosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNovoProjeto;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JComboBox<String> cbProjeto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbProjeto;
    private javax.swing.JTable tbArq;
    private javax.swing.JTable tbProjetos;
    // End of variables declaration//GEN-END:variables
}
