/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fluigdocdev.views;

import fluigdocdev.SqliteConnect;
import fluigdocdev.entidades.ArqProjet;
import fluigdocdev.entidades.Cliente;
import fluigdocdev.entidades.Config;
import fluigdocdev.entidades.Projeto;
import fluigdocdev.entidades.DocPoi;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author rogerio
 */
public class CriarDoc extends javax.swing.JInternalFrame {

    SqliteConnect sql = new SqliteConnect();
    Config conf = new Config();
    Cliente cli = new Cliente();
    Projeto proj = new Projeto();
    ArqProjet arq = new ArqProjet();

    /**
     * Creates new form CriarDoc
     */
    public CriarDoc() {
        initComponents();
        loadCbProjt();
    }

    private void loadCbProjt() {
        try {
            this.cbCliente.setModel(sql.getResultComboBoxModel(cli.getSelNomeCli()));
            this.txtPathDest.setText(conf.getCreateDoc());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCliente = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox<>();
        lbProjeto = new javax.swing.JLabel();
        cbProjeto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtPathDest = new javax.swing.JTextField();
        btCriar = new javax.swing.JButton();
        cbListDoc = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Criação de Documento de Projeto");

        lbCliente.setText("Cliente:");

        cbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClienteActionPerformed(evt);
            }
        });

        lbProjeto.setText("Projeto:");

        jLabel1.setText("Pasta Destino:");

        btCriar.setText("Criar");
        btCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarActionPerformed(evt);
            }
        });

        cbListDoc.setText("Listar todos os documentos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbProjeto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPathDest)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cbListDoc)
                                .addGap(276, 276, 276)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCliente)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbProjeto)
                    .addComponent(cbProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPathDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCriar)
                    .addComponent(cbListDoc))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClienteActionPerformed
        // TODO add your handling code here:
        String descCli = (String) this.cbCliente.getSelectedItem();
        cli.setNome(descCli);
        try {
            this.cbProjeto.setModel(this.proj.getArqModelCB(descCli));
        } catch (Exception e) {
            System.err.println("Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_cbClienteActionPerformed

    private void btCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarActionPerformed
        // TODO add your handling code here:
        String descCli = (String) this.cbCliente.getSelectedItem();
        String descProj = (String) this.cbProjeto.getSelectedItem();        
        if (!descCli.equals("Selecione") && !descProj.equals("Selecione") && !descProj.equals("null")) {
            DocPoi doc = new DocPoi();
            doc.setInfoDoc(
                      //txtPathDest.getText()
                      conf.getCreateDoc() + "/" +descProj + ".docx"
                    , descCli
                    , descProj
                    ,this.cbListDoc.isSelected()
            );
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione Primeio o Cliente e Projeto");
        }
    }//GEN-LAST:event_btCriarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCriar;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JCheckBox cbListDoc;
    private javax.swing.JComboBox<String> cbProjeto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbProjeto;
    private javax.swing.JTextField txtPathDest;
    // End of variables declaration//GEN-END:variables
}
