/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fluigdocdev.views;

import javax.swing.JOptionPane;

/**
 *
 * @author rogerio
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        miCriarDoc = new javax.swing.JMenuItem();
        miCriarPacProj = new javax.swing.JMenuItem();
        miImportDataset = new javax.swing.JMenuItem();
        mnCadastro = new javax.swing.JMenu();
        miCadCli = new javax.swing.JMenuItem();
        miCadProj = new javax.swing.JMenuItem();
        miCadServ = new javax.swing.JMenuItem();
        mnConfig = new javax.swing.JMenu();
        miConfGeral = new javax.swing.JMenuItem();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fluig Doc Dev");
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(750, 500));

        jDesktopPane1.setDesktopManager(null);
        jDesktopPane1.setName("jDesktopPane1"); // NOI18N

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        mnArquivo.setText("Arquivo");
        mnArquivo.setName("mnArquivo"); // NOI18N

        miCriarDoc.setText("Criar Documento do Projeto");
        miCriarDoc.setName("miCriarDoc"); // NOI18N
        miCriarDoc.addActionListener(formListener);
        mnArquivo.add(miCriarDoc);

        miCriarPacProj.setText("Criar Pacote do Projeto");
        miCriarPacProj.setName("miCriarPacProj"); // NOI18N
        miCriarPacProj.addActionListener(formListener);
        mnArquivo.add(miCriarPacProj);

        miImportDataset.setText("Importação de Datasets");
        miImportDataset.setName("miImportDataset"); // NOI18N
        miImportDataset.addActionListener(formListener);
        mnArquivo.add(miImportDataset);

        jMenuBar1.add(mnArquivo);

        mnCadastro.setText("Cadastro");
        mnCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mnCadastro.setName("mnCadastro"); // NOI18N

        miCadCli.setText("Clientes");
        miCadCli.setName("miCadCli"); // NOI18N
        miCadCli.addActionListener(formListener);
        mnCadastro.add(miCadCli);

        miCadProj.setText("Projetos");
        miCadProj.setName("miCadProj"); // NOI18N
        miCadProj.addActionListener(formListener);
        mnCadastro.add(miCadProj);

        miCadServ.setText("Server");
        miCadServ.setName("miCadServ"); // NOI18N
        miCadServ.addActionListener(formListener);
        mnCadastro.add(miCadServ);

        jMenuBar1.add(mnCadastro);

        mnConfig.setText("Configuração");
        mnConfig.setName("mnConfig"); // NOI18N

        miConfGeral.setText("Geral");
        miConfGeral.setName("miConfGeral"); // NOI18N
        miConfGeral.addActionListener(formListener);
        mnConfig.add(miConfGeral);

        jMenuBar1.add(mnConfig);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == miCriarDoc) {
                TelaPrincipal.this.miCriarDocActionPerformed(evt);
            }
            else if (evt.getSource() == miCriarPacProj) {
                TelaPrincipal.this.miCriarPacProjActionPerformed(evt);
            }
            else if (evt.getSource() == miCadCli) {
                TelaPrincipal.this.miCadCliActionPerformed(evt);
            }
            else if (evt.getSource() == miCadProj) {
                TelaPrincipal.this.miCadProjActionPerformed(evt);
            }
            else if (evt.getSource() == miCadServ) {
                TelaPrincipal.this.miCadServActionPerformed(evt);
            }
            else if (evt.getSource() == miConfGeral) {
                TelaPrincipal.this.miConfGeralActionPerformed(evt);
            }
            else if (evt.getSource() == miImportDataset) {
                TelaPrincipal.this.miImportDatasetActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void miCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadCliActionPerformed
        CadastroCliente tela = new CadastroCliente();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_miCadCliActionPerformed

    private void miCadServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadServActionPerformed
        CadastroServer tela = new CadastroServer();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_miCadServActionPerformed

    private void miCadProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadProjActionPerformed
        CadastroProjeto tela = new CadastroProjeto();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_miCadProjActionPerformed

    private void miCriarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCriarDocActionPerformed
        // TODO add your handling code here:
        CriarDoc tela = new CriarDoc();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_miCriarDocActionPerformed

    private void miCriarPacProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCriarPacProjActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Em Construção");
    }//GEN-LAST:event_miCriarPacProjActionPerformed

    private void miConfGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConfGeralActionPerformed
        // TODO add your handling code here:
        TelaConfig tela = new TelaConfig();
        jDesktopPane1.add(tela);
        tela.setVisible(true);        
    }//GEN-LAST:event_miConfGeralActionPerformed

    private void miImportDatasetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miImportDatasetActionPerformed
        // TODO add your handling code here:        
        ImportProject tela = new ImportProject();
        jDesktopPane1.add(tela);
        tela.setVisible(true);        
    }//GEN-LAST:event_miImportDatasetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miCadCli;
    private javax.swing.JMenuItem miCadProj;
    private javax.swing.JMenuItem miCadServ;
    private javax.swing.JMenuItem miConfGeral;
    private javax.swing.JMenuItem miCriarDoc;
    private javax.swing.JMenuItem miCriarPacProj;
    private javax.swing.JMenuItem miImportDataset;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JMenu mnCadastro;
    private javax.swing.JMenu mnConfig;
    // End of variables declaration//GEN-END:variables
}
